# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:/home/just/.local/bin:$PATH
# export PATH="/home/just/.pyenv/bin:$PATH"
# eval "$(pyenv virtualenv-init -)"


# # Nvim Manpager in Nvim else bat
# if [ -n "${NVIM_LISTEN_ADDRESS+x}" ]; then
#   export MANPAGER="/usr/local/bin/nvr -c 'Man!' -o -"
# else
#   export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
# fi

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# export PAGER=batcat
# alias cat=batcat
# alias bat=batcat
# # alias mux=tmuxinator
# alias zshconfig="$EDITOR ~/.zshrc"
# alias ohmyzsh="$EDITOR ~/.oh-my-zsh"
# eval "$(rbenv init -)"
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
# export PATH=/home/just/go/bin:/home/just/.config/nvm/versions/node/v17.8.0/bin:/home/just/tools/lua-language-server/bin/Linux:/home/just/.pyenv/plugins/pyenv-virtualenv/shims:/home/just/.rbenv/shims:/home/just/.cargo/bin:/home/just/.pyenv/shims:/home/just/.pyenv/bin:/usr/bin:/home/just/.local/kitty.app/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/go/bin
