# .zshenv is sourced on all invocations of the shell, unless the -f option is set.
# It should contain commands to set the command search path, plus other important environment variables.
# .zshenv' should not contain commands that produce output or assume the shell is attached to a tty.

export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache

export CARGO_HOME=$HOME/.local/share/cargo
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export GEM_HOME="${XDG_DATA_HOME}"/gem
export GEM_SPEC_CACHE="${XDG_CACHE_HOME}"/gem
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export GOPATH="$XDG_DATA_HOME"/go
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export KDEHOME="$XDG_CONFIG_HOME"/kde
export LESSHISTFILE="${XDG_CACHE_HOME}"/less/history
export MYSQL_HISTFILE="$XDG_DATA_HOME"/mysql_history
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export PYENV_ROOT="$XDG_DATA_HOME"/pyenv
export PYTHONSTARTUP="${XDG_CONFIG_HOME}/python/pythonrc"
export RBENV_ROOT="$XDG_DATA_HOME"/rbenv
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export SDKMAN_DIR="$XDG_DATA_HOME"/sdkman
export VAGRANT_HOME="$XDG_DATA_HOME"/vagrant
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
export _Z_DATA="$XDG_DATA_HOME/z"

. "$CARGO_HOME/env"
